### ISSUE TITLE
Update to Node.js LTS

### ISSUE THREAD

**Issue by MattIPv4** [twitter-together/action#196]
**What’s missing?**

The project should be running on the latest LTS release of Node.js.

**Why?**

The project currently runs on Node.js 12 which was EOL'ed as of April this year. 

**Alternatives you tried**

N/A

**Comment by gr2m** [comment]
Agree, I just did it on a ton of repositories using https://github.com/gr2m/octoherd-script-bump-node-version-in-workflows, setting `--node-version "lts/*"`, but not yet on my personal account. Doing it right now

**Comment by gr2m** [comment]
actually nevermind, I miss understood. I bump the used node versions in CI via https://github.com/gr2m/twitter-together/commit/f7123bba7b6467cc115a603963ddf694eae032ac, but your issue is about bundling the action code itself, right? 

`runs.using` in `action.yml` can now be set to nod16 as per https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-nodejs-v16, do you want to send a pull request?

**Comment by MattIPv4** [comment]
It's a bit of both -- updating the action to use Node 16, but also updating the repo to it (setting an .nvmrc file for it [I'm introducing at a v12 in #177], and updating to lockfile v2)
